services:

  postgres:
    image: postgres:16
    container_name: cloudtask-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cloudtask
      POSTGRES_PASSWORD: cloudtask_dev
      POSTGRES_DB: cloudtask
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: cloudtask-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: